### ISSUE TITLE
Page 'https://hacktoberfest.circleci.com/#/crystalBall' does not load properly

### ISSUE THREAD

**Issue by Saamiyah** [CircleCI-Public/Orb-Policies#9]
![image](https://user-images.githubusercontent.com/7201256/66452499-c5aa7f00-ea71-11e9-87d0-2d646db8a9e8.png)

**Comment by lokst** [comment]
Thanks for the report, closing this as I believe this issue might have been resolved already.
I would encourage filing future issues in the official repository for the CircleCI hacktoberfest site: https://github.com/CircleCI-Public/hacktoberfest 🙂
